# Generated by Django 5.2.8 on 2025-12-18 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('target_type', models.CharField(choices=[('GUIDE', 'Руководство'), ('ANNOUNCEMENT', 'Объявление')], max_length=15, verbose_name='Тип объекта')),
                ('target_title', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.announcement')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'История активности',
                'ordering': ['-created_at'],
            },
        ),
    ]
