# Generated by Django 5.2.8 on 2026-03-18 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_chatmessage_options_chatmessage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_reviews',
            field=models.BooleanField(default=True, verbose_name='Разрешить отзывы'),
        ),
        migrations.AlterField(
            model_name='favoriteannouncement',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.announcement'),
        ),
        migrations.AlterField(
            model_name='favoriteannouncement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
