# Generated by Django 5.2.8 on 2026-03-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_allow_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
