# Generated by Django 5.2.8 on 2026-03-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_banner_image_profile_banner_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='banner_style',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vk',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube',
        ),
    ]
