# Generated by Django 5.2.8 on 2026-03-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_blocked_at_profile_blocked_reason_and_more'),
        ('users', '0015_profile_banner_image_profile_banner_style_and_more'),
    ]

    operations = [
    ]
