# Generated by Django 5.2.8 on 2026-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20260322_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
